name: Deploy .NET app to Azure

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch
  pull_request:
    branches:
      - main  # Trigger deployment on pull request to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # You can also use 'windows-latest' depending on your setup
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checks out the repository code
    
    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'  # Change to your desired .NET version

    - name: Restore dependencies
      run: dotnet restore  # Restores the NuGet packages

    - name: Build the application
      run: dotnet build --configuration Release  # Builds the app in release mode

    - name: Publish the application
      run: dotnet publish --configuration Release --output ./publish  # Publishes the app

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app-artifact
        path: ./publish  # Uploads the published files for deployment
    
  deploy:
    runs-on: ubuntu-latest  # You can use 'windows-latest' as well
    needs: build  # Ensure that the build job runs first
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Download build artifact
      uses: actions/download-artifact@v2
      with:
        name: app-artifact  # Downloads the artifact from the build job
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: <your-app-name>  # Replace with your Azure Web App name
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}  # Publish profile from Azure
        package: ./publish  # Path to the published app
